export type ServiceData = {
  slug: string;
  title: string;
  tagline: string;
  desc: string;
  iconName: string;
  color: "cyan" | "purple" | "gold" | "pink";
  heroStats: { num: string; label: string }[];
  features: { title: string; desc: string; points: string[] }[];
  process: { title: string; desc: string }[];
  techStack: { category: string; items: string[] }[];
  whyStats: { num: string; label: string }[];
};

export const servicesData: ServiceData[] = [
  {
    slug: "web-development",
    title: "Website Development",
    tagline: "Professional Website Development Services",
    desc: "Transform your digital presence with cutting-edge web technologies, responsive design, and exceptional user experiences that drive business growth and customer engagement.",
    iconName: "Globe",
    color: "cyan",
    heroStats: [
      { num: "300%", label: "Average ROI Increase" },
      { num: "75%", label: "More Lead Generation" },
      { num: "99.9%", label: "Uptime Guarantee" },
      { num: "24/7", label: "Expert Support" },
    ],
    features: [
      { title: "Lightning Fast Performance", desc: "Optimized websites that load in under 3 seconds, ensuring excellent user experience and better search engine rankings.", points: ["Advanced caching strategies", "Image optimization & compression", "CDN integration", "Core Web Vitals optimized"] },
      { title: "Mobile-First Responsive Design", desc: "Websites that look stunning and function perfectly across all devices, from smartphones to desktops.", points: ["Touch-friendly interfaces", "Flexible grid layouts", "Adaptive images & media", "Cross-browser compatibility"] },
      { title: "Enterprise-Grade Security", desc: "Advanced security measures to protect your website and user data from modern cyber threats.", points: ["SSL encryption & HTTPS", "SQL injection prevention", "Regular security audits", "DDoS protection"] },
      { title: "SEO & Analytics Ready", desc: "Built-in SEO optimization and analytics integration to maximize your online visibility and track success.", points: ["Search engine optimization", "Google Analytics integration", "Performance monitoring", "Conversion tracking setup"] },
      { title: "Easy Content Management", desc: "User-friendly content management systems that allow you to update your website without technical knowledge.", points: ["Intuitive admin dashboard", "Drag & drop page builder", "Media library management", "User role management"] },
      { title: "Ongoing Support & Updates", desc: "Comprehensive maintenance and support services to keep your website running smoothly and up-to-date.", points: ["Regular software updates", "24/7 technical support", "Performance optimization", "Bug fixes & improvements"] },
    ],
    process: [
      { title: "Discovery & Planning", desc: "We start by understanding your business goals, target audience, and project requirements to create a comprehensive development strategy." },
      { title: "Design & Prototyping", desc: "Creating wireframes, mockups, and interactive prototypes to visualize the final product before development begins." },
      { title: "Development & Coding", desc: "Building your website using cutting-edge technologies, following best practices for performance, security, and scalability." },
      { title: "Testing & Quality Assurance", desc: "Rigorous testing across devices, browsers, and scenarios to ensure flawless functionality and user experience." },
      { title: "Launch & Deployment", desc: "Smooth deployment to production servers with proper configuration, monitoring, and performance optimization." },
      { title: "Support & Maintenance", desc: "Ongoing support, updates, and maintenance to keep your website secure, fast, and up-to-date with latest technologies." },
    ],
    techStack: [
      { category: "Frontend", items: ["React.js", "Next.js", "Vue.js", "Angular", "TypeScript", "Tailwind CSS"] },
      { category: "Backend", items: ["Node.js", "Express.js", "Python / Django", "PHP / Laravel", "Java Spring", ".NET Core"] },
      { category: "Database", items: ["MongoDB", "PostgreSQL", "MySQL", "Redis", "Firebase", "SQLite"] },
      { category: "Cloud & DevOps", items: ["AWS", "Google Cloud", "Microsoft Azure", "Docker", "Kubernetes", "Vercel"] },
    ],
    whyStats: [
      { num: "78+", label: "Websites Delivered" },
      { num: "45+", label: "Happy Clients" },
      { num: "99%", label: "Client Satisfaction" },
      { num: "2+", label: "Years Experience" },
    ],
  },
  {
    slug: "mobile-apps",
    title: "Mobile & Web Apps",
    tagline: "Custom Mobile & Web Application Development",
    desc: "Build powerful, scalable mobile and web applications that engage users, streamline operations, and drive business growth across all platforms.",
    iconName: "Smartphone",
    color: "purple",
    heroStats: [
      { num: "50+", label: "Apps Delivered" },
      { num: "4.8★", label: "Average App Rating" },
      { num: "99%", label: "Crash-Free Rate" },
      { num: "24/7", label: "Support Available" },
    ],
    features: [
      { title: "Native Android Development", desc: "High-performance Android apps built with Kotlin and Java for the best native experience.", points: ["Kotlin & Java expertise", "Material Design UI", "Google Play deployment", "Push notifications"] },
      { title: "iOS App Development", desc: "Elegant iOS applications built with Swift for iPhone and iPad users.", points: ["Swift & Objective-C", "Apple HIG compliance", "App Store deployment", "Face ID & Touch ID"] },
      { title: "Cross-Platform Apps", desc: "Build once, deploy everywhere with React Native and Flutter.", points: ["React Native", "Flutter development", "Shared codebase", "Native performance"] },
      { title: "Progressive Web Apps", desc: "Web apps that feel like native apps with offline support and push notifications.", points: ["Offline functionality", "App-like experience", "Fast loading", "Installable on devices"] },
      { title: "API Integration", desc: "Seamless integration with third-party services, payment gateways, and enterprise systems.", points: ["REST & GraphQL APIs", "Payment gateways", "Social login", "Maps & location"] },
      { title: "App Maintenance", desc: "Ongoing updates, bug fixes, and feature enhancements to keep your app competitive.", points: ["Regular OS updates", "Performance tuning", "Feature additions", "Analytics & monitoring"] },
    ],
    process: [
      { title: "Requirement Analysis", desc: "Deep dive into your app idea, target users, and business objectives to define the perfect solution." },
      { title: "UI/UX Design", desc: "Creating intuitive, beautiful interfaces that users love, with wireframes and interactive prototypes." },
      { title: "Agile Development", desc: "Iterative development in sprints, delivering working features regularly for your feedback." },
      { title: "Quality Testing", desc: "Comprehensive testing on real devices to ensure performance, security, and reliability." },
      { title: "App Store Launch", desc: "Handling the complete submission process for Google Play Store and Apple App Store." },
      { title: "Post-Launch Support", desc: "Monitoring, updates, and enhancements to keep your app growing after launch." },
    ],
    techStack: [
      { category: "Mobile", items: ["React Native", "Flutter", "Swift", "Kotlin", "Java", "Objective-C"] },
      { category: "Frontend", items: ["React.js", "Next.js", "TypeScript", "Tailwind CSS", "Redux", "Zustand"] },
      { category: "Backend", items: ["Node.js", "Firebase", "Supabase", "Python", "GraphQL", "REST APIs"] },
      { category: "Tools", items: ["Xcode", "Android Studio", "Figma", "Postman", "TestFlight", "Firebase Analytics"] },
    ],
    whyStats: [
      { num: "50+", label: "Apps Built" },
      { num: "4.8★", label: "Avg Rating" },
      { num: "99%", label: "Satisfaction" },
      { num: "2+", label: "Years Exp." },
    ],
  },
  {
    slug: "digital-marketing",
    title: "Digital Marketing",
    tagline: "Data-Driven Digital Marketing Services",
    desc: "Grow your brand, reach your audience, and drive measurable results with our comprehensive digital marketing strategies tailored for your business.",
    iconName: "Megaphone",
    color: "gold",
    heroStats: [
      { num: "3x", label: "Average ROI" },
      { num: "200%", label: "Traffic Growth" },
      { num: "60%", label: "Lead Increase" },
      { num: "45+", label: "Brands Grown" },
    ],
    features: [
      { title: "Search Engine Optimization", desc: "Rank higher on Google and drive organic traffic that converts into real customers.", points: ["Keyword research & strategy", "On-page & off-page SEO", "Technical SEO audits", "Local SEO optimization"] },
      { title: "Google & Meta Ads", desc: "Targeted paid advertising campaigns that maximize your budget and deliver measurable ROI.", points: ["Google Search & Display Ads", "Facebook & Instagram Ads", "Retargeting campaigns", "A/B testing & optimization"] },
      { title: "Social Media Marketing", desc: "Build a strong social presence and engage your audience across all major platforms.", points: ["Content strategy & creation", "Community management", "Influencer partnerships", "Social media analytics"] },
      { title: "Content Marketing", desc: "Compelling content that educates, engages, and converts your target audience.", points: ["Blog writing & SEO content", "Video scripts & production", "Infographics & visuals", "Email newsletters"] },
      { title: "Email Marketing", desc: "Automated email campaigns that nurture leads and drive repeat business.", points: ["Campaign automation", "Segmentation & personalization", "A/B testing", "Performance analytics"] },
      { title: "Analytics & Reporting", desc: "Transparent reporting with actionable insights to continuously improve your marketing performance.", points: ["Monthly performance reports", "Conversion tracking", "Competitor analysis", "ROI measurement"] },
    ],
    process: [
      { title: "Audit & Research", desc: "Comprehensive analysis of your current digital presence, competitors, and market opportunities." },
      { title: "Strategy Development", desc: "Creating a customized marketing roadmap aligned with your business goals and budget." },
      { title: "Campaign Setup", desc: "Setting up all channels, tracking, and creative assets for maximum campaign effectiveness." },
      { title: "Launch & Execute", desc: "Launching campaigns with continuous monitoring and real-time optimization." },
      { title: "Analyze & Optimize", desc: "Deep analysis of performance data to identify what works and scale successful strategies." },
      { title: "Report & Scale", desc: "Regular reporting with clear insights and recommendations to grow your marketing investment." },
    ],
    techStack: [
      { category: "SEO Tools", items: ["SEMrush", "Ahrefs", "Google Search Console", "Moz", "Screaming Frog", "Yoast"] },
      { category: "Paid Ads", items: ["Google Ads", "Meta Ads Manager", "LinkedIn Ads", "YouTube Ads", "Twitter Ads"] },
      { category: "Analytics", items: ["Google Analytics 4", "Hotjar", "Mixpanel", "Facebook Pixel", "Tag Manager"] },
      { category: "Automation", items: ["Mailchimp", "HubSpot", "Zapier", "Buffer", "Hootsuite", "ActiveCampaign"] },
    ],
    whyStats: [
      { num: "3x", label: "Avg ROI" },
      { num: "200%", label: "Traffic Growth" },
      { num: "45+", label: "Brands Grown" },
      { num: "99%", label: "Satisfaction" },
    ],
  },
  {
    slug: "branding-design",
    title: "Branding & Design",
    tagline: "Creative Branding & UI/UX Design Services",
    desc: "Build a powerful brand identity that resonates with your audience and sets you apart from the competition with our creative design solutions.",
    iconName: "Palette",
    color: "pink",
    heroStats: [
      { num: "100+", label: "Brands Created" },
      { num: "98%", label: "Client Approval" },
      { num: "48hr", label: "First Draft" },
      { num: "∞", label: "Revisions" },
    ],
    features: [
      { title: "Logo & Brand Identity", desc: "Memorable logos and complete brand identity systems that tell your story.", points: ["Logo design & variations", "Color palette & typography", "Brand guidelines document", "Business card & stationery"] },
      { title: "UI/UX Design", desc: "Intuitive, beautiful interfaces that delight users and drive conversions.", points: ["User research & personas", "Wireframing & prototyping", "Visual design systems", "Usability testing"] },
      { title: "Marketing Collateral", desc: "Professional marketing materials that reinforce your brand across all touchpoints.", points: ["Brochures & flyers", "Social media templates", "Presentation decks", "Banner & ad creatives"] },
      { title: "Motion Graphics", desc: "Engaging animations and motion graphics that bring your brand to life.", points: ["Logo animations", "Social media reels", "Explainer videos", "UI micro-animations"] },
      { title: "Packaging Design", desc: "Eye-catching product packaging that stands out on shelves and online.", points: ["Product label design", "Box & packaging design", "3D mockups", "Print-ready files"] },
      { title: "Brand Strategy", desc: "Strategic brand positioning that connects emotionally with your target audience.", points: ["Brand voice & tone", "Competitor analysis", "Target audience research", "Brand story development"] },
    ],
    process: [
      { title: "Discovery & Brief", desc: "Understanding your brand vision, values, target audience, and competitive landscape." },
      { title: "Research & Moodboard", desc: "Market research, competitor analysis, and creating visual direction moodboards." },
      { title: "Concept Development", desc: "Developing multiple creative concepts for your review and feedback." },
      { title: "Design & Refine", desc: "Refining the chosen concept with your feedback until it's perfect." },
      { title: "Final Delivery", desc: "Delivering all final files in multiple formats ready for print and digital use." },
      { title: "Brand Guidelines", desc: "Creating a comprehensive brand guidelines document for consistent usage." },
    ],
    techStack: [
      { category: "Design Tools", items: ["Adobe Illustrator", "Adobe Photoshop", "Figma", "Adobe XD", "Sketch", "InDesign"] },
      { category: "Motion", items: ["Adobe After Effects", "Adobe Premiere", "Lottie", "Rive", "Spline", "Blender"] },
      { category: "Prototyping", items: ["Figma Prototypes", "InVision", "Marvel", "Framer", "Principle", "ProtoPie"] },
      { category: "Collaboration", items: ["Notion", "Miro", "Zeplin", "Abstract", "Loom", "Slack"] },
    ],
    whyStats: [
      { num: "100+", label: "Brands Created" },
      { num: "98%", label: "Approval Rate" },
      { num: "48hr", label: "First Draft" },
      { num: "45+", label: "Happy Clients" },
    ],
  },
  {
    slug: "software-erp",
    title: "Software & ERP Solutions",
    tagline: "Custom Software & ERP Development",
    desc: "Streamline your business operations with custom software solutions and enterprise-grade ERP systems designed specifically for your workflow.",
    iconName: "Monitor",
    color: "cyan",
    heroStats: [
      { num: "40%", label: "Efficiency Gain" },
      { num: "60%", label: "Cost Reduction" },
      { num: "99.9%", label: "System Uptime" },
      { num: "24/7", label: "Support" },
    ],
    features: [
      { title: "Custom ERP Systems", desc: "Tailored ERP solutions that fit your exact business processes and workflows.", points: ["Inventory management", "HR & payroll module", "Finance & accounting", "Supply chain management"] },
      { title: "CRM Solutions", desc: "Customer relationship management systems to track leads, sales, and customer interactions.", points: ["Lead & pipeline management", "Customer 360 view", "Sales automation", "Reporting & analytics"] },
      { title: "Business Automation", desc: "Automate repetitive tasks and workflows to save time and reduce human error.", points: ["Workflow automation", "Document management", "Approval workflows", "Scheduled reporting"] },
      { title: "Cloud-Based Applications", desc: "Scalable cloud applications accessible from anywhere, on any device.", points: ["Multi-tenant architecture", "Role-based access control", "Real-time collaboration", "Automatic backups"] },
      { title: "Data Analytics & BI", desc: "Turn your business data into actionable insights with powerful dashboards.", points: ["Custom dashboards", "Real-time reporting", "Data visualization", "Predictive analytics"] },
      { title: "System Integration", desc: "Connect your existing tools and systems for seamless data flow across your organization.", points: ["API integrations", "Legacy system migration", "Third-party connectors", "Data synchronization"] },
    ],
    process: [
      { title: "Business Analysis", desc: "Deep understanding of your current processes, pain points, and automation opportunities." },
      { title: "Solution Architecture", desc: "Designing the technical architecture and database schema for your custom solution." },
      { title: "Agile Development", desc: "Building in sprints with regular demos to ensure the solution meets your expectations." },
      { title: "Data Migration", desc: "Safely migrating your existing data to the new system with zero data loss." },
      { title: "Training & Onboarding", desc: "Comprehensive training for your team to ensure smooth adoption of the new system." },
      { title: "Go-Live & Support", desc: "Managed go-live process with dedicated support during the critical transition period." },
    ],
    techStack: [
      { category: "Backend", items: ["Node.js", "Python", "Java Spring", "PHP Laravel", ".NET Core", "Go"] },
      { category: "Frontend", items: ["React.js", "Angular", "Vue.js", "TypeScript", "Tailwind CSS", "Material UI"] },
      { category: "Database", items: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "Oracle"] },
      { category: "Infrastructure", items: ["AWS", "Docker", "Kubernetes", "Nginx", "RabbitMQ", "Apache Kafka"] },
    ],
    whyStats: [
      { num: "40%", label: "Efficiency Gain" },
      { num: "60%", label: "Cost Reduction" },
      { num: "30+", label: "Systems Built" },
      { num: "99.9%", label: "Uptime" },
    ],
  },
  {
    slug: "ai-automation",
    title: "AI & Automation",
    tagline: "Intelligent AI & Automation Solutions",
    desc: "Harness the power of artificial intelligence and automation to transform your business operations, enhance customer experiences, and stay ahead of the competition.",
    iconName: "Bot",
    color: "purple",
    heroStats: [
      { num: "80%", label: "Task Automation" },
      { num: "5x", label: "Productivity Boost" },
      { num: "24/7", label: "AI Availability" },
      { num: "60%", label: "Cost Savings" },
    ],
    features: [
      { title: "AI Chatbots", desc: "Intelligent conversational AI that handles customer queries 24/7 with human-like responses.", points: ["Natural language processing", "Multi-language support", "CRM integration", "Escalation to human agents"] },
      { title: "Process Automation (RPA)", desc: "Robotic Process Automation to eliminate repetitive manual tasks and reduce errors.", points: ["Data entry automation", "Invoice processing", "Report generation", "Email automation"] },
      { title: "Machine Learning Models", desc: "Custom ML models trained on your data to make intelligent predictions and decisions.", points: ["Predictive analytics", "Recommendation engines", "Fraud detection", "Demand forecasting"] },
      { title: "Computer Vision", desc: "AI-powered image and video analysis for quality control, security, and more.", points: ["Object detection", "Face recognition", "Document scanning", "Quality inspection"] },
      { title: "Natural Language Processing", desc: "Extract insights from text data, automate content, and understand customer sentiment.", points: ["Sentiment analysis", "Text classification", "Auto-summarization", "Content generation"] },
      { title: "AI Integration", desc: "Integrate powerful AI APIs like OpenAI, Google AI, and AWS AI into your existing systems.", points: ["OpenAI / GPT integration", "Google AI services", "AWS AI/ML services", "Custom model deployment"] },
    ],
    process: [
      { title: "AI Readiness Assessment", desc: "Evaluating your data, processes, and infrastructure to identify the best AI opportunities." },
      { title: "Use Case Definition", desc: "Defining specific AI use cases with clear success metrics and ROI projections." },
      { title: "Data Preparation", desc: "Collecting, cleaning, and preparing your data for model training and validation." },
      { title: "Model Development", desc: "Building, training, and fine-tuning AI models using the latest techniques and frameworks." },
      { title: "Integration & Testing", desc: "Integrating AI solutions into your existing systems with thorough testing and validation." },
      { title: "Monitor & Improve", desc: "Continuous monitoring of AI performance with regular updates and model improvements." },
    ],
    techStack: [
      { category: "AI / ML", items: ["Python", "TensorFlow", "PyTorch", "Scikit-learn", "OpenAI API", "LangChain"] },
      { category: "Automation", items: ["UiPath", "Automation Anywhere", "n8n", "Zapier", "Make", "Node-RED"] },
      { category: "Data", items: ["Apache Spark", "Pandas", "NumPy", "Jupyter", "Airflow", "dbt"] },
      { category: "Cloud AI", items: ["AWS SageMaker", "Google Vertex AI", "Azure ML", "Hugging Face", "Pinecone"] },
    ],
    whyStats: [
      { num: "80%", label: "Tasks Automated" },
      { num: "5x", label: "Productivity" },
      { num: "60%", label: "Cost Savings" },
      { num: "24/7", label: "AI Uptime" },
    ],
  },
  {
    slug: "ecommerce",
    title: "E-commerce Solutions",
    tagline: "High-Converting E-commerce Development",
    desc: "Build powerful online stores that attract customers, drive sales, and scale with your business growth using the latest e-commerce technologies.",
    iconName: "ShoppingCart",
    color: "gold",
    heroStats: [
      { num: "250%", label: "Sales Increase" },
      { num: "40%", label: "Cart Recovery" },
      { num: "99.9%", label: "Store Uptime" },
      { num: "24/7", label: "Support" },
    ],
    features: [
      { title: "Custom Online Stores", desc: "Fully custom e-commerce websites built for performance, conversions, and brand identity.", points: ["Custom product pages", "Advanced filtering & search", "Wishlist & comparison", "Multi-currency support"] },
      { title: "Shopify & WooCommerce", desc: "Expert development on leading e-commerce platforms for faster time-to-market.", points: ["Shopify theme development", "WooCommerce customization", "Plugin development", "Platform migration"] },
      { title: "Payment Integration", desc: "Secure, seamless payment processing with multiple gateway options.", points: ["Razorpay & PayU", "Stripe & PayPal", "UPI & net banking", "EMI & BNPL options"] },
      { title: "Inventory Management", desc: "Smart inventory systems to track stock, manage suppliers, and prevent overselling.", points: ["Real-time stock tracking", "Low stock alerts", "Supplier management", "Multi-warehouse support"] },
      { title: "Mobile Commerce", desc: "Mobile-optimized shopping experiences and dedicated shopping apps.", points: ["Mobile-first design", "PWA shopping app", "One-tap checkout", "Push notifications"] },
      { title: "Analytics & Growth", desc: "Data-driven insights to understand customer behavior and optimize for more sales.", points: ["Sales analytics dashboard", "Customer behavior tracking", "Abandoned cart recovery", "Conversion optimization"] },
    ],
    process: [
      { title: "Store Strategy", desc: "Planning your product catalog, target audience, and e-commerce strategy for maximum sales." },
      { title: "Design & UX", desc: "Creating a shopping experience that builds trust and makes buying effortless." },
      { title: "Development", desc: "Building your store with all features, payment gateways, and third-party integrations." },
      { title: "Product Setup", desc: "Setting up your product catalog, categories, pricing, and inventory management." },
      { title: "Testing & Launch", desc: "Complete testing of checkout flows, payments, and performance before going live." },
      { title: "Growth & Optimization", desc: "Ongoing CRO, SEO, and marketing support to continuously grow your sales." },
    ],
    techStack: [
      { category: "Platforms", items: ["Shopify", "WooCommerce", "Magento", "BigCommerce", "Custom Next.js", "Medusa.js"] },
      { category: "Payments", items: ["Razorpay", "Stripe", "PayPal", "PayU", "Cashfree", "CCAvenue"] },
      { category: "Marketing", items: ["Google Shopping", "Meta Catalog", "Klaviyo", "Mailchimp", "Omnisend", "Yotpo"] },
      { category: "Analytics", items: ["Google Analytics 4", "Hotjar", "Lucky Orange", "Clarity", "Facebook Pixel"] },
    ],
    whyStats: [
      { num: "250%", label: "Sales Increase" },
      { num: "40%", label: "Cart Recovery" },
      { num: "30+", label: "Stores Built" },
      { num: "99%", label: "Satisfaction" },
    ],
  },
];

export const serviceSlugMap: Record<string, string> = {
  "Web Development": "/services/web-development",
  "Mobile & Web Apps": "/services/mobile-apps",
  "Digital Marketing": "/services/digital-marketing",
  "Branding & Design": "/services/branding-design",
  "Software & ERP": "/services/software-erp",
  "AI & Automation": "/services/ai-automation",
  "E-commerce": "/services/ecommerce",
};
